barometer asp.net mvc/barometer (asp.net mvc)/Models/Convertables/InfoGraphics.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace barometer.Models.Convertables
{
    public class InfoGraphics
    {
        public string Alias { get; set; }
        public int Sum { get; set; }
    }
}

barometer asp.net mvc/barometer (asp.net mvc)/Models/ViewModel/InfoGraphicViewModel.cs
using barometer.Models.Convertables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace barometer.Models.ViewModel
{
    public class InfoGraphicViewModel
    {
        public List<InfoGraphics> Data { get; set;}
        public List<InfoGraphicsHeader> Header { get; set; }
        public int Year { get; set; }
        public string NameMonth { get; set; }
    }
}

barometer asp.net mvc/barometer (asp.net mvc)/Controllers/Api/InfoGraphicsController.cs
using barometer.Helpers;
using barometer.Models.Convertables;
using barometer.Models.Database;
using barometer.Models.ViewModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace barometer.Controllers.Api
{
    [Authorize]
    public class InfoGraphicsController : ApiController
    {
        private readonly BarometerDbContext context;

        public InfoGraphicsController()
        {
            context = new BarometerDbContext();
        }


    }
}

barometer asp.net mvc/barometer (asp.net mvc)/Controllers/FeedbackController.cs
using barometer.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace barometer.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
        [HttpPost]
        public JsonResult Upload(FeedbackViewModel model)
        {
            MailMessage message = new MailMessage("support@barometer.lviv.ua", "info@barometer.lviv.ua")
            {
                Subject = "barometer.lviv.ua - зворотній зв'язок",
                BodyEncoding = Encoding.UTF8,
                Body = model.ToString() + "User: " + User.Identity.Name,
                IsBodyHtml = true,
                SubjectEncoding = Encoding.UTF8,
            };

            if (model.FileUpload != null)
            {
                var extension = Path.GetExtension(model.FileUpload.FileName).ToLower();
                if (extension != ".jpg" && extension != ".png")
                {
                    return Json(new { Warning = "Допустимі формати png або jpeg! " });
                }

                // Create  the file attachment for this e-mail message.
                Attachment data = new Attachment(model.FileUpload.InputStream, model.FileUpload.FileName);

                message.Attachments.Add(data);
            }
           
            SmtpClient client = new SmtpClient
            {
                DeliveryMethod = SmtpDeliveryMethod.Network
            };
            client.Send(message);

            return Json(new { Success = "Дані успішно відправлені!" });
        }
    }
}

barometer asp.net mvc/barometer (asp.net mvc)/Controllers/OperatorsController.cs
using barometer.Helpers;
using barometer.Models.Database;
using barometer.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace barometer.Controllers
{
    [Authorize(Roles="Operator,Admin")]
    public class OperatorsController : Controller
    {
        private readonly BarometerDbContext context;

        public OperatorsController()
        {
            context = new BarometerDbContext();
        }

        public ActionResult Statistics()
        {
            var model = CommonHelper.GetPeriods(context);
            return View(model);
        }

        [HttpGet]
        public ActionResult Comments()
        {
            var model = CommentsHelper.GetCommentsViewModel(context);
            return View(model);
        }

        [HttpGet]
        public ActionResult GetCommentModalView(int? id)
        {
            var model = CommentsHelper.GetEditCommentViewModel(id.GetValueOrDefault(), context, User.Identity.Name, User.IsInRole("Operator"));
            return PartialView("Partial/_EditComment", model);
        }
    }
}

barometer asp.net mvc/barometer (asp.net mvc)/Controllers/ReviewOfDataController.cs
using barometer.Helpers;
using barometer.Models.Database;
using barometer.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace barometer.Controllers
{
    public class ReviewOfDataController : Controller
    {
        private readonly BarometerDbContext context;

        public ReviewOfDataController()
        {
            context = new BarometerDbContext();
        }

        [HttpPost]
        public JsonResult GetTableData(ReviewOfDataViewModel model)
        {
            return Json(new
            {
                data = ReviewOfDataHelper.GetTableData(model, context)
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetTableColumn(int periodFirst, int periodSecond)
        {
            return Json(ReviewOfDataHelper.GetTableColumn(periodFirst, periodSecond, context), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Operator,Admin")]
        [HttpPost]
        public ActionResult GetReviewOfDataReport(int year)
        {
            var file = File(ReviewOfDataHelper.GetReviewOfDataReport(year, context), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Огляд даних - " + year + ".xlsx");
            Response.AddHeader("Set-Cookie", "filedownload=true; path=/; expires=5000;");
            return file;
        }
    }
}

barometer asp.net mvc/barometer (asp.net mvc)/Controllers/TICDataController.cs
using barometer.Helpers;
using barometer.Models.Business.Report;
using barometer.Models.Convertables;
using barometer.Models.Database;
using barometer.Models.Enums;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace barometer.Controllers
{
    [Authorize(Roles = "TIC")]
    public class TICDataController : Controller
    {
        private readonly BarometerDbContext context;
        public TICDataController()
        {
            context = new BarometerDbContext();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadReport()
        {
            if (Request.Files.Count > 0)
            {
                var extension = Path.GetExtension(Request.Files[0].FileName).ToLower();
                if (extension != ".csv" && extension != ".xls" && extension != ".xlsx")
                {
                    return Json(new { WarningMessage = "Допустимі формати xls/xlsx/csv!" });
                }

                using (var transactionContext = context.Database.BeginTransaction())
                {
                    try
                    {
                        HttpPostedFileBase file = Request.Files[0];
                        string fileName = file.FileName;
                        string fileContentType = file.ContentType;
                        byte[] fileBytes = new byte[file.ContentLength];
                        var listNotExsist = new List<Tuple<int, string>>();
                        var data = file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                        using (var package = new ExcelPackage(file.InputStream))
                        {
                            var currentSheet = package.Workbook.Worksheets;
                            var workSheet = currentSheet.First();
                            var noOfCol = workSheet.Dimension.End.Column;
                            var noOfRow = workSheet.Dimension.End.Row;
                            var workCells = workSheet.Cells;
                            var listForUpdate = new List<TICDataClause>();
                            var user = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                            string separator = CultureInfo.CurrentCulture.DateTimeFormat.DateSeparator;
                            var startDate = new DateTime(2012, 7,1);
                            int suborderEmpty = 0;
                            TICData ticData = null;
                            string outName = null;
                            Data dbData = null;

                            for (int rowIterator = 1; rowIterator <= noOfRow; rowIterator++)
                            {
                                outName = (workCells[rowIterator, 1].Text ?? string.Empty).Trim();
                                var country = context.Country.FirstOrDefault(x => x.Name == outName);
                                var region = context.Region.FirstOrDefault(x => x.Name == outName);
                                var city = context.City.FirstOrDefault(x => x.Name == outName);
                                if (country != null || region != null || city != null)
                                {
                                    var dateTime = DateTime.ParseExact(workCells[rowIterator, 13].Text, "dd" + separator + "MM" + separator + "yyyy HH:mm:ss", CultureInfo.InvariantCulture);
                                    ticData = context.TICData.FirstOrDefault(x => x.DateVisit.Equals(dateTime) && x.User.UserName == User.Identity.Name);

                                    if (ticData == null)
                                    {
                                        ticData = new TICData();
                                        ticData.Created = DateTime.Now;
                                        context.TICData.Add(ticData);
                                    }

                                    ticData.City = city;
                                    ticData.Region = (region == null && ticData.City != null) ? ticData.City.Region : region;
                                    ticData.Country = (country == null && ticData.Region != null) ? ticData.Region.Country : country;
                                    ticData.CountTourists = Convert.ToInt32(workCells[rowIterator, 2].Value);
                                    ticData.Sex = Convert.ToString(workCells[rowIterator, 3].Value) == "ч" ? Sex.Male : Convert.ToString(workCells[rowIterator, 3].Value) == "ж" ? Sex.Female : Sex.MaleFemale;
                                    ticData.Events = Convert.ToInt32(workCells[rowIterator, 4].Value);
                                    ticData.PrintingIndustry = Convert.ToInt32(workCells[rowIterator, 5].Value);
                                    ticData.Souvenirs = Convert.ToInt32(workCells[rowIterator, 6].Value);
                                    ticData.Excursions = Convert.ToInt32(workCells[rowIterator, 7].Value);
                                    ticData.Museums = Convert.ToInt32(workCells[rowIterator, 8].Value);
                                    ticData.Food = Convert.ToInt32(workCells[rowIterator, 9].Value);
                                    ticData.ReferenceInformation = Convert.ToInt32(workCells[rowIterator, 10].Value);
                                    ticData.Residence = Convert.ToInt32(workCells[rowIterator, 11].Value);
                                    ticData.Transport = Convert.ToInt32(workCells[rowIterator, 12].Value);
                                    ticData.DateVisit = dateTime;
                                    ticData.Changed = DateTime.Now;
                                    ticData.User = user;

                                    if (ticData.DateVisit >= startDate && !listForUpdate.Any(x => x.CountryId == ticData.Country.Id && x.Month == ticData.DateVisit.Month
                                       && x.Year == ticData.DateVisit.Year))
                                    {
                                        listForUpdate.Add(new TICDataClause()
                                        {
                                            CountryId = ticData.Country.Id,
                                            Month = ticData.DateVisit.Month,
                                            Year = ticData.DateVisit.Year
                                        });
                                    }
                                }
                                else
                                {
                                    if (string.IsNullOrEmpty(outName))
                                    {
                                        if (suborderEmpty + 1 <= 10)
                                        {
                                            suborderEmpty++;
                                        }
                                        else
                                        {
                                            break;
                                        }
                                    }
                                    else
                                    {
                                        suborderEmpty = 0;
                                    }
                                    listNotExsist.Add(new Tuple<int, string>(rowIterator, outName));
                                }
                            }
                            context.SaveChanges();

                            int sum = 0;
                            Data dataRow = null;
                            foreach (var item in listForUpdate)
                            {
                                sum = context.TICData.Where(x => x.Country.Id == item.CountryId && x.DateVisit.Month == item.Month
                                       && x.DateVisit.Year == item.Year && x.User.UserName == user.UserName).Sum(x => x.CountTourists);
                                dataRow = context.Data.FirstOrDefault(x => x.Country.Id == item.CountryId && x.Period.StartDate.Month == item.Month
                                       && x.Period.StartDate.Year == item.Year && x.User.UserName == user.UserName);

                                if (dataRow != null)
                                {
                                    dataRow.Value = sum;
                                    dataRow.Changed = DateTime.Now;
                                }
                                else
                                {
                                    dataRow = new Data();

                                    dataRow.Period = context.Period.FirstOrDefault(x => x.StartDate.Month == item.Month
                                    && x.StartDate.Year == item.Year);
                                    dataRow.User = user;
                                    dataRow.Country = context.Country.FirstOrDefault(x => x.Id == item.CountryId);
                                    dataRow.Value = sum;
                                    dataRow.TypeData = context.TypeData.FirstOrDefault(x => x.Id == (short)TypeDataEnum.HotelAndHostelAndTIC);
                                    dataRow.Created = DateTime.Now;
                                    dataRow.Changed = DateTime.Now;

                                    context.Data.Add(dataRow);
                                }
                            }

                            context.SaveChanges();
                            transactionContext.Commit();
                        }
                        return Json(new { SuccessMessage = "Файл успішно імпортованно!", ListNotExsist = listNotExsist });
                    }
                    catch (Exception ex)
                    {
                        transactionContext.Rollback();

barometer asp.net mvc/barometer (asp.net mvc)/Views/Shared/NotImplement.cshtml
@{
    ViewBag.Title = "Огляд даних - barometer.lviv.ua";
}

<h3 class="text-danger text-center">Вибачте за незручності!</h3>
<h3 class="text-danger text-center">Огляд даних Ви зможете здійснити через декілька днів</h3>
<h3 class="text-danger text-center">Середню завантаженість закладу Ви можете переглянути в @Html.ActionLink("Benchmarking", "Benchmarking", "Home")</h3>
<h3 class="text-danger text-center">Дякуємо за розуміння!</h3>

barometer asp.net mvc/barometer (asp.net mvc)/Views/Shared/_InfoGraphics.cshtml
@using barometer.Models.ViewModel;
@model InfoGraphicViewModel

<div class="info-graphics">
    <table>
        <colgroup>
            <col span="1" class="first_column">
            <col span="1" class="second_column">
            <col span="1" class="third_column">
            <col span="1" class="fourth_column">
            <col span="1" class="fifth_column">
            <col span="1" class="sixth_column">
            <col span="1" class="seventh_column">
            <col span="1" class="eighth_column">
            <col span="1" class="nineth_column">
            <col span="1" class="tenth_column">
            <col span="1" class="eleventh_column">
            <col span="1" class="twelfth_column">
            <col span="1" class="thirteenth_column">
        </colgroup>
        <thead>
            <tr>
                <th></th>
                @for (int i = 0; i < Model.Header.Count; i++)
                {
                    <th class="count">
                        <div>@Model.Header[i].Count</div>
                    </th>
                    <th class="sum">
                        <div>
                            @Model.Header[i].Sum
                            <img src='@Url.Content("~/Content/images/" + (Model.Header[i].IsRaise ? "raise" : "fall") + ".png")' width='8' height='11'>
                        </div>
                    </th>
                    if (i == 1)
                    { 
                        <th class="date-info">
                            <div>
                                <p>@Model.NameMonth</p>
                                <p>@Model.Year</p>
                            </div>
                        </th>
                    }
                    else
                    {
                        <th></th>
                    }

                }
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Data.Count / 4; i++)
            {
                <tr>
                    <td></td>
                    <td class="flag">
                        @if(!string.IsNullOrEmpty(Model.Data[i].Alias))
                        { 
                            <img src='@Url.Content("~/Content/images/countries/" + Model.Data[i].Alias + ".png")' width='24' height='24'>
                        }
                    </td>
                    <td>
                        <div>@Model.Data[i].Sum</div>
                    </td>
                    <td></td>
                    <td class="flag">
                        @if(!string.IsNullOrEmpty(Model.Data[i+5].Alias))
                        { 
                            <img src='@Url.Content("~/Content/images/countries/" + Model.Data[i + 5].Alias + ".png")' width='24' height='24'>
                        }
                    </td>
                    <td>
                        <div>@Model.Data[i + 5].Sum</div>
                    </td>
                    @if (i == 0)
                    { 
                        <td rowspan="5">
                            <div class="info">
                                <p class="top">ТОП 5 КРАЇН</p>
                                <p class="count">КІЛЬКІСТЬ ГОСТЕЙ</p>
                            </div>
                        </td>
                    }
                    <td class="flag">
                        @if (!string.IsNullOrEmpty(Model.Data[i+10].Alias))
                        { 
                            <img src='@Url.Content("~/Content/images/countries/" + Model.Data[i + 10].Alias + ".png")' width='24' height='24'>
                        }
                    </td>
                    <td>
                        <div>@Model.Data[i + 10].Sum</div>
                    </td>
                    <td></td>
                    <td class="flag">
                        @if (!string.IsNullOrEmpty(Model.Data[i+15].Alias))
                        { 
                            <img src='@Url.Content("~/Content/images/countries/" + Model.Data[i + 15].Alias + ".png")' width='24' height='24'>
                        }
                    </td>
                    <td>
                        <div>@Model.Data[i + 15].Sum</div>
                    </td>
                    <td></td>
                </tr>
            }
        <tbody>
    </table>
</div>
<div class="clearfix"></div>
<p class="info-graphics-about no-padding-left"><img src="@Url.Content("~/Content/images/about-arrow.png")" width="11" height="8">завантаженість збільшилась/зменшилась в порівнянні з аналогічним місяцем попереднього року</p>

barometer asp.net mvc/barometer (asp.net mvc)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Barometer Lviv</title>
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    @Styles.Render("~/Content/css")
    @Styles.Render("https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css")
    @Styles.Render("~/Content/toastr.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="container static-container">
            <a href="http://www.touristinfo.lviv.ua/" target="_blank" class="logo logo-first pull-left">
                <p class="pull-right text-left">
                    Центр туристичної інформації
                </p>
            </a>
            <a href="@Url.Action("Index","Home")" class="logo logo-second pull-left"></a>
            @if (User.Identity.IsAuthenticated)
            {
                @Html.Partial("_NavbarHelp")
            }
        </div>
    </header>
    <div class="clearfix"></div>
    <main>
        <div class="container main-container static-container">
            @if(User.Identity.IsAuthenticated)
            {
                @Html.Partial("_Navbar")
            }
            @RenderBody()
        </div>
    </main>
    <div class="clearfix"></div>
    <footer>
        <div class="container static-container no-padding-left">
            <ul class="info list-unstyled">
                <li class="logo_footer">
                    <p>Центр туристичної інформації</p>
                </li>
                <div class="clearfix"></div>
                <li>Tel.: +38(032) 254 60 84</li>
                <li><a href="mailto:info@barometer.lviv.ua">info@barometer.lviv.ua</a></li>
                <li><a href="https://barometer.lviv.ua">barometer.lviv.ua</a></li>
                <li><a href="http://www.touristinfo.lviv.ua">touristinfo.lviv.ua</a></li>
                <li><a href="http://lviv.travel">lviv.travel</a></li>
            </ul>
        </div>
    </footer>
    <div id="changePasswordModalPlace"></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/dropzone")
    @Scripts.Render("~/Scripts/toastr.min.js")
    @Scripts.Render("http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js")
    @Scripts.Render("http://cdn.datatables.net/plug-ins/1.10.12/sorting/date-de.js")
    @Scripts.Render("http://cdn.datatables.net/plug-ins/1.10.12/api/sum().js")
    @Scripts.Render("https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js")
    @Scripts.Render("https://www.gstatic.com/charts/loader.js");
    @Scripts.Render("~/bundles/main")
    @Scripts.Render("~/bundles/changePassword")
    @RenderSection("Scripts", false)
</body>
</html>

barometer asp.net mvc/barometer (asp.net mvc)/Views/Shared/_Navbar.cshtml
@using barometer.Extensions.HtmlHelpers
<nav class="navbar">
    <div class="container no-padding static-container">
        <div class="collapse navbar-collapse no-padding">
            <ul class="nav navbar-nav">
                @if(!User.IsInRole("Operator"))
                {
                    <li>@Html.MenuActionLink("Введення даних", "InsertData", "Home")</li>
                }
                <li>@Html.MenuActionLink("Огляд даних", "ReviewOfData", "Home")</li>
                <li>@Html.MenuActionLink("Benchmarking", "Benchmarking", "Home")</li>
                <li>@Html.MenuActionLink("Зворотній зв'язок", "Feedback", "Home")</li>
                <li>@Html.MenuActionLink("Інфографіка", "InfoGraphics", "Home")</li>
                <li>@Html.MenuActionLink("Особиста інформація", "EditUserData", "Account")</li>
                @if(User.IsInRole("TIC"))
                {
                    <li>@Html.MenuActionLink("Відвідини", "Index", "TICData")</li>
                }
                @if(User.IsInRole("Operator"))
                {
                    <li>@Html.MenuActionLink("Коментарі", "Comments", "Operators")</li>
                    <li>@Html.MenuActionLink("Статистика", "Statistics", "Operators")</li>
                    <li>@Html.MenuActionLink("Реєстрація", "Register", "Account")</li>
                }
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

barometer asp.net mvc/barometer (asp.net mvc)/Views/Shared/_NavbarHelp.cshtml
@using barometer.Helpers
<nav class="navbar-help navbar pull-right">
    <div class="user-name pull-right">
        Ви увійшли як @CommonHelper.GetFullName(User.Identity.Name)</div>
        <div class="no-padding">
            <div class="collapse navbar-collapse no-padding">
                <ul class="nav navbar-nav pull-right">
                    <li><a target="blank" href="@Url.Content("~/Content/pdf/Про проект 2017.pdf")">Про проект</a></li>
                    <li><a target="blank" href="@Url.Content("~/Content/pdf/Туристичний барометер. Договір про співпрацю 2017.pdf")">Договір про співпрацю</a></li>
                    <li><a href="javascript:void(0)" id="changePasswordLink">Змінити пароль</a></li>
                    <li><a href="javascript:void(0)" id="logOff">Вихід</a></li>

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
</nav>
<form action="@Url.Action("LogOff", "Account")" method="POST" id="logOffPOST">
    @Html.AntiForgeryToken()
</form>